# ============================================================
# Copyright (C) 2025 Hjuanma
#
# This source code is licensed under the Common Sense License
# (CSL) v1.1.
#
# You may obtain a copy of the license at:
# https://github.com/shmaplex/csl
#
# Large-Scale Commercial Users must comply with contribution
# requirements described in Section 8 of the License.
# ============================================================

MD_TEMPLATES = {
    'header': """# Nmap Scan Report

**Scanner:** {scanner}
**Command:** `{command}`
**Start time:** {start_time}

## Methodology & Available Data

The following features were **enabled** (flags present in the command):
{enabled_features}

""",
    'host_discovery_header': "## Host Discovery\n\n",
    'host_info_row': "- **Status:** {status} (reason: {reason})\n- **IPv4:** {ipv4}\n- **IPv6:** {ipv6}\n- **MAC:** {mac}\n- **Hostname:** {hostname}\n",
    'enabled_feature': "- {feature}\n",
    'open_ports_header': "## Open Ports\n\n",
    'open_ports_table': "| Port | Protocol | Service | Product | Version |\n|------|----------|---------|---------|---------|\n",
    'open_ports_row': "| {portid} | {protocol} | {service_name} | {product} | {version} |\n",
    'no_open_ports': "*No open ports found.*\n",
    'os_detection_header': "## Operating System Detection\n\n",
    'os_table_header': "| OS Match | Accuracy |\n|----------|----------|\n",
    'os_row': "| {name} | {accuracy}% |\n",
    'os_not_scanned': "**--NO SCANNED--** (flag `-O` or `-A` not used)\n",
    'os_no_matches': "*No OS matches found (maybe `-O` used but no fingerprint).*\n",
    'vuln_header': "## Vulnerability Scan (Script vuln)\n\n",
    'vuln_not_scanned': "**--NO SCANNED--** (flag `--script vuln` not used)\n",
    'vuln_table_header': "| CVE | Script | Output snippet |\n|-----|--------|----------------|\n",
    'vuln_row': "| {cve} | {script} | {snippet} |\n",
    'vuln_no_found': "*No vulnerabilities (CVEs) reported by the vuln scripts.*\n",
    'vuln_more': "\n*... and {remaining} more CVEs.*\n",
    'limitations_header': "## Limitations & Notes\n\n",
    'limitation_all_ports': "- **Port range:** Only top 1000 ports were scanned (`-p-` not used). Some services on non‑standard ports may be missing.\n",
    'limitation_udp': "- **UDP ports:** Not scanned (`-sU` not used).\n",
    'limitation_traceroute': "- **Traceroute:** Not performed (`--traceroute` not used).\n",
    'limitation_default_scripts': "- **Default scripts:** Not run (`-sC` or `-A` not used).\n",
    'footer': "\n---\n*Report generated by nmap_report_generator*\n"
}